
list(APPEND COMPILE_DEFINITIONS BOOT_FB)

list(APPEND SOURCE
    ${CMAKE_CURRENT_LIST_DIR}/framebuf.h
    ${CMAKE_CURRENT_LIST_DIR}/bootvid.c)

list(APPEND COMPILE_DEFINITIONS
    $<$<COMPILE_LANGUAGE:RC>:REACTOS_STR_FILE_DESCRIPTION="Generic Linear FrameBuffer Boot Driver">)
